#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a kitty desktop='^1' state=floating rectangle="960x540+25+75" follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off


setxkbmap es
#zsh ~/.config/polybar/launch.sh --cuts
picom &
polybar -r bar_up &
polybar -r bar_down &
xrandr --output eDP1 --primary --auto --output HDMI1 --auto --right-of DP1 --output DP1 --auto --right-of eDP1
feh --bg-fill ~/Images/wallpapers/rei-ayanami.png
spotifyd --verbose --no-daemon -b pulseaudio -d echuxamePixa -u raulgilabertgamez -p Raul.2003 &


bspc monitor -d I II III IV V VI VII VIII IX X
